### ISSUE TITLE
Cascading calls should not remove the first stack

### ISSUE THREAD

**Issue by flibustenet** [romanyx/stack#1]
We loose the stack when the error is wrapped in cascade

```go
package main

import (
	"fmt"

	"github.com/pkg/errors"
	"github.com/romanyx/stack"
)

func a() error {
	return errors.New("a")
}
func b() error {
	return stack.Errorf("b :%v", a())
}
func c() error {
	return stack.Errorf("c :%v", b())
}
func main() {
	err := c()
	for _, frame := range stack.Trace(err) {
		fmt.Printf("%s:%d %s()\n", frame.File, frame.Line, frame.Function)
	}
}
```

Result

```go
/tmp/t/t.go:17 main.c()
/tmp/t/t.go:20 main.main()
```

With `pkg/errors` it's the opposite, the stack is three time. I would prefer to have full stack like that

```go
/tmp/t/t.go:10 main.a()
/tmp/t/t.go:13 main.b()
/tmp/t/t.go:16 main.c()
/tmp/t/t.go:19 main.main()
```

**Comment by romanyx** [comment]
Hi, you should use `%w` verb to wrap an error, so instead of `return stack.Errorf("b: %v", a())` you'll get `return stack.Errorf("b: %w", a())` and the output will be:

```
/tmp/t/t.go:14 main.b()
/tmp/t/t.go:17 main.c()
/tmp/t/t.go:20 main.main()
```

Also, it won't print `main.a()` as it's not wrapped in any way, the package might need something like `stack.New(error)` but I'm not sure about that. For now, you can use `fmt.Errorf("%w", errors.New("a"))`, if you really need to save that frame.

**Comment by flibustenet** [comment]
I see, thanks
